config/routes.rb
Rails.application.routes.draw do
  get 'instagrams/index'
  post 'instagrams/upload'

  resources :instagrams
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :instagram
end

app/models/instagram.rb
class Instagram < ApplicationRecord
  validates :image, presence: true
  mount_uploader :image,  ImageUploader

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
 end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :instagrams, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
    @favorite = current_user.favorites.where(user_id: current_user.id)
    render layout: 'favorite'
  end

  def create
    favorite = current_user.favorites.create(instagram_id: params[:instagram_id])
    redirect_to instagram_path(params[:instagram_id]), notice: "#{favorite.instagram.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(instagram_id: params[:instagram_id]).destroy
    redirect_to instagram_path(params[:instagram_id]), notice: "#{favorite.instagram.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/instagrams_controller.rb
class InstagramsController < ApplicationController
  before_action :set_instagram, only: [:show, :edit, :update, :destroy]

  def index
    @Instagram = Instagram.new
    @image = Instagram.all
  end

  def show
    @favorite = current_user.favorites.find_by(instagram_id: @instagram.id)
  end

  def edit
  end

  def update
    if @instagram.update(instagram_update_params)
      redirect_to instagrams_index_path
    else
      render 'index'
    end
  end

  def upload
    @Instagram = Instagram.new(instagram_params)
    if @Instagram.save
      ContactMailer.contact_mail(@Instagram,current_user).deliver
      redirect_to instagrams_index_path
    else
      render 'index'
    end
  end

  def destroy
    @instagram.destroy
    redirect_to instagrams_index_path
  end

  private
  def instagram_params
    params.require(:instagram).permit(:user_id, :content, :image)
  end

  def instagram_update_params
    params.require(:instagram).permit(:user_id, :content)
  end

  def set_instagram
  @instagram = Instagram.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render layout: 'login'
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to instagrams_index_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to instagrams_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render layout: 'login'
  end
  def create
    
    @user = User.new(user_params)

    if @user.save
      redirect_to instagrams_index_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/instagrams_helper.rb
module InstagramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/show.html.erb
<div class="row">
  <div class="col-1"></div>
  <div class="col-10 row">
    <% if @favorite == nil %>
      <h3>お気に入りがありません。</h3>
    <% else %>
      <% @favorite.reverse_each do |insta| %>
        <div class="col-md-4 col-sm-12 row-eq-height">
        <%= link_to instagram_path(insta.instagram.id) do %>
        <%= image_tag insta.instagram.image_url , style: 'height:auto;width:100%;'%>
        <% end %>
      </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-1"></div>
</div>

app/views/instagrams/_form.html.erb
<%= form_with(model: @Instagram, local: true,url: instagrams_upload_path) do |form| %>


<div class="field">

  <%= form.hidden_field :user_id, :value => current_user.id %>

  <%= form.label "画像選択" %><br>
  <%= form.file_field :image %><br>
  <%= form.text_area :content %><br>

  <%= form.submit "投稿" ,style: 'height:auto;width: 20%;' %>
</div>

<% end %>

app/views/instagrams/edit.html.erb
<article class="content">
  <div class = "content_image"><%= image_tag @instagram.image_url , style: 'height:auto;width:100%;'%></div>
    <%= form_with(model: @instagram,scope: :instagram,method: :patch, local: true , url: instagram_path, html: { class: 'input-form'}) do |form| %>
    <div class = "form_textarea"><%= form.text_area :content %></div>
    <div class = "content_submit"><%= form.submit "編集" ,style: 'height:auto;width: 100%;'%></div>

    <% end %>
    <br>
    <%= link_to '戻る',instagram_path(@instagram.id),method: :get %>

</article>

app/views/instagrams/index.html.erb

<% if logged_in? %>
<%= render 'form' %>
<% end %>

<hr>

<div class="preview" />

</div>
<div class="row">
  <div class="col-1"></div>
  <div class="col-10 row">

    <% Instagram.all.reverse_each do |insta| %>
    <div class="col-md-4 col-sm-12 row-eq-height">
      <%= link_to instagram_path(insta.id) do %>
      <%= image_tag insta.image_url , style: 'height:auto;width:100%;'%>
      <% end %>
      <hr>
    </div>
    <% end %>
  </div>
  <div class="col-1"></div>
</div>

app/views/instagrams/show.html.erb
<article class = "content">
  <div class = "content_image"><%= image_tag @instagram.image_url , style: 'height:auto;width:100%;'%></div>
  <h3><%= @instagram.user.name %>
  <% unless @instagram.user == current_user %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(instagram_id: @instagram.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(instagram_id: @instagram.id), method: :post, class: 'btn btn-prymary' %>
    <% end %>
  <% else %>
  <%= link_to "編集", edit_instagram_path(@instagram.id),class: 'btn btn-prymary' %>
  <%= link_to '削除', instagram_path(@instagram.id), method: :delete ,class: 'btn btn-prymary'%>
  <% end %>
  </h3>

  <p class = "content_p"><%= @instagram.content %></p>
  <br>
  <%= link_to '戻る',instagrams_path %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <header class="header clearfix">
      <nav>
        <div class="row">
          <div class="col-2"><%= button_to "お気に入り", favorite_path(current_user.id) ,method: :get,:class => "btn btn-outline-primary" %></div>
          <div class="col-2"><%= button_to "ログアウト"  ,session_path(current_user.id) ,local: true, scope: :session ,method: :delete ,:class => "btn btn-outline-primary"%></div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <% else %>
    <header class="header clearfix">
      <nav>
        <div class="row">
          <div class="col-4"><%= button_to "アカウントを作成する", new_user_path ,:class => "btn btn-outline-primary", method: :get %></div>
        </div>
      </nav>
    </header>

    <%= image_tag("insta_top.png" , class: "top_image clearfix")  %>

    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <div class="top_form">
    <h1>ログイン</h1>
    <%= form_with(scope: :session, url: sessions_path) do |f| %>
    <table>
      <tr>
        <th><%= f.label :Eメール %></th>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <th><%= f.label :パスワード %></th>
        <td><%= f.password_field :password %></td>
      </tr>
    </table>
    <br>
    <%= f.submit "ログイン" %>

  </div>

    <% end %>

    <% end %>


    <footer class="footer">
      <p>名前：栗本 裕基  　　受講時期：2017/8/1 ～　</p>
    </footer>
  </body>
</html>

app/views/layouts/favorite.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <header class="header clearfix">
      <nav>
        <div class="row">
          <div class="col-2"><%= button_to "全表示", instagrams_path,method: :get,:class => "btn btn-outline-primary" %></div>
          <div class="col-2"><%= button_to "ログアウト"  ,session_path(current_user.id) ,local: true, scope: :session ,method: :delete ,:class => "btn btn-outline-primary"%></div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <% else %>
    <header class="header clearfix">
      <nav>
        <div class="row">
          <div class="col-4"><%= button_to "アカウントを作成する", new_user_path ,:class => "btn btn-outline-primary", method: :get %></div>
        </div>
      </nav>
    </header>

    <%= image_tag("insta_top.png" , class: "top_image clearfix")  %>

    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <div class="top_form">
    <h1>ログイン</h1>
    <%= form_with(scope: :session, url: sessions_path) do |f| %>
    <table>
      <tr>
        <th><%= f.label :Eメール %></th>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <th><%= f.label :パスワード %></th>
        <td><%= f.password_field :password %></td>
      </tr>
    </table>
    <br>
    <%= f.submit "ログイン" %>

  </div>

    <% end %>

    <% end %>


    <footer class="footer">
      <p>名前：栗本 裕基  　　受講時期：2017/8/1 ～　</p>
    </footer>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <header class="header clearfix">
      <nav>
        <div class="row">
          <div class="col-2"><%= button_to "お気に入り", favorite_path(current_user.id) ,method: :get,:class => "btn btn-outline-primary" %></div>
          <div class="col-2"><%= button_to "ログアウト"  ,session_path(current_user.id) ,local: true, scope: :session ,method: :delete ,:class => "btn btn-outline-primary"%></div>
        </div>
      </nav>
    </header>
    <% else %>
    <header class="header clearfix">
      <nav>
        <div class="row">
          <div class="col-4"><%= button_to "アカウントを作成する", new_user_path ,:class => "btn btn-outline-primary" %></div>
        </div>
      </nav>
    </header>
    <% end %>

    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <%= yield %>
    <footer class="footer">
      <p>名前：栗本 裕基  　　受講時期：2017/8/1 ～　</p>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<h1>アカウント作成</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br>
<%= form_with(model: @user, local: true ,url: users_path, method: :post,scope: :user) do |f| %>
  <%= f.label "名前" %><br>
  <%= f.text_field :name %>
  <br>
  <%= f.label "メールアドレス" %><br>
  <%= f.email_field :email %>
  <br>
  <%= f.label "パスワード" %><br>
  <%= f.password_field :password %>
  <br>
  <%= f.label "パスワード確認" %><br>
  <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit "アカウント作成" %>
  <br>
  <%= link_to '戻る',instagrams_path %>

<% end %>